version: '3.3'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=polls
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prisma:
    image: prismagraphql/prisma:1.34
    ports:
      - 4466:4466
    environment:
      - PRISMA_CONFIG=/app/prisma/prisma.yml
    volumes:
      - prisma_data:/app/prisma

volumes:
  postgres_data:
  prisma_data:
